### ISSUE TITLE
My animation doesn't play 

### ISSUE THREAD

**Issue by bedryck** [2d-inc/Flare-React#13]
I am able to render the animation JSON (.flr) but it does not run the animation. The animation just shows up as a static image. I think I'm doing something wrong

**Comment by bedryck** [comment]
![image](https://user-images.githubusercontent.com/22659468/62086016-b8009e00-b265-11e9-87ab-a8e83815a6d2.png) code

**Comment by bedryck** [comment]
![image](https://user-images.githubusercontent.com/22659468/62086058-dd8da780-b265-11e9-8541-f500575d1090.png)
![image](https://user-images.githubusercontent.com/22659468/62086081-f39b6800-b265-11e9-835f-fdfd42c4e7a3.png)

**Comment by luigi-rosso** [comment]
It looks like your animation is actually named "Untitled". Try replacing the ```animationName="check"``` with ```animationName="Untitled"```.

**Comment by bedryck** [comment]
Oh, I realized my mistake. Thank you very much, now it works
